language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install -U pip setuptools wheel
    - pip install -U -e .[dev]
    - pip install -U -r requirements-optional.txt

script:
    - pytest
