language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
install: 
    - pip install -r requirements.txt
    - pip install -r requirements-optional.txt
script: python setup.py develop && python setup.py test

